/**
 * Data Kota/Kabupaten se-Indonesia dengan koordinat
 * Dikelompokkan berdasarkan provinsi untuk kemudahan pencarian
 */

export interface City {
  id: string;
  name: string;
  latitude: number;
  longitude: number;
}

export interface Province {
  id: string;
  name: string;
  cities: City[];
}

export const provinces: Province[] = [
  {
    id: "aceh",
    name: "Aceh",
    cities: [
      {
        id: "banda-aceh",
        name: "Kota Banda Aceh",
        latitude: 5.5483,
        longitude: 95.3238,
      },
      {
        id: "sabang",
        name: "Kota Sabang",
        latitude: 5.8933,
        longitude: 95.3164,
      },
      {
        id: "langsa",
        name: "Kota Langsa",
        latitude: 4.4683,
        longitude: 97.9681,
      },
      {
        id: "lhokseumawe",
        name: "Kota Lhokseumawe",
        latitude: 5.1801,
        longitude: 97.1507,
      },
      {
        id: "subulussalam",
        name: "Kota Subulussalam",
        latitude: 2.6417,
        longitude: 98.0167,
      },
      {
        id: "aceh-besar",
        name: "Kab. Aceh Besar",
        latitude: 5.3819,
        longitude: 95.5208,
      },
      {
        id: "aceh-barat",
        name: "Kab. Aceh Barat",
        latitude: 4.4511,
        longitude: 96.1708,
      },
      {
        id: "aceh-selatan",
        name: "Kab. Aceh Selatan",
        latitude: 3.1811,
        longitude: 97.4428,
      },
      {
        id: "aceh-tenggara",
        name: "Kab. Aceh Tenggara",
        latitude: 3.2956,
        longitude: 97.7239,
      },
      {
        id: "aceh-timur",
        name: "Kab. Aceh Timur",
        latitude: 4.6333,
        longitude: 97.7833,
      },
      {
        id: "aceh-utara",
        name: "Kab. Aceh Utara",
        latitude: 5.0,
        longitude: 97.1333,
      },
      { id: "pidie", name: "Kab. Pidie", latitude: 5.0708, longitude: 96.1572 },
    ],
  },
  {
    id: "sumut",
    name: "Sumatera Utara",
    cities: [
      { id: "medan", name: "Kota Medan", latitude: 3.5952, longitude: 98.6722 },
      { id: "binjai", name: "Kota Binjai", latitude: 3.6, longitude: 98.4833 },
      {
        id: "pematangsiantar",
        name: "Kota Pematangsiantar",
        latitude: 2.9667,
        longitude: 99.0667,
      },
      {
        id: "tebingtinggi",
        name: "Kota Tebing Tinggi",
        latitude: 3.3167,
        longitude: 99.15,
      },
      {
        id: "padangsidempuan",
        name: "Kota Padang Sidempuan",
        latitude: 1.3833,
        longitude: 99.2667,
      },
      {
        id: "gunungsitoli",
        name: "Kota Gunungsitoli",
        latitude: 1.2833,
        longitude: 97.6167,
      },
      {
        id: "sibolga",
        name: "Kota Sibolga",
        latitude: 1.7333,
        longitude: 98.7833,
      },
      {
        id: "tanjungbalai",
        name: "Kota Tanjung Balai",
        latitude: 2.9667,
        longitude: 99.8,
      },
      {
        id: "deli-serdang",
        name: "Kab. Deli Serdang",
        latitude: 3.4167,
        longitude: 98.9167,
      },
      {
        id: "langkat",
        name: "Kab. Langkat",
        latitude: 3.7667,
        longitude: 98.2833,
      },
      { id: "karo", name: "Kab. Karo", latitude: 3.1, longitude: 98.3833 },
      {
        id: "simalungun",
        name: "Kab. Simalungun",
        latitude: 2.95,
        longitude: 99.0,
      },
      {
        id: "asahan",
        name: "Kab. Asahan",
        latitude: 2.8667,
        longitude: 99.6333,
      },
      {
        id: "labuhanbatu",
        name: "Kab. Labuhanbatu",
        latitude: 2.25,
        longitude: 100.05,
      },
      {
        id: "tapanuli-utara",
        name: "Kab. Tapanuli Utara",
        latitude: 2.0167,
        longitude: 98.9333,
      },
      {
        id: "tapanuli-tengah",
        name: "Kab. Tapanuli Tengah",
        latitude: 1.9167,
        longitude: 98.6667,
      },
      {
        id: "tapanuli-selatan",
        name: "Kab. Tapanuli Selatan",
        latitude: 1.55,
        longitude: 99.3333,
      },
      { id: "nias", name: "Kab. Nias", latitude: 1.0333, longitude: 97.7833 },
      {
        id: "samosir",
        name: "Kab. Samosir",
        latitude: 2.6167,
        longitude: 98.75,
      },
      { id: "toba", name: "Kab. Toba", latitude: 2.5, longitude: 99.05 },
    ],
  },
  {
    id: "sumbar",
    name: "Sumatera Barat",
    cities: [
      {
        id: "padang",
        name: "Kota Padang",
        latitude: -0.9471,
        longitude: 100.4172,
      },
      {
        id: "bukittinggi",
        name: "Kota Bukittinggi",
        latitude: -0.3056,
        longitude: 100.3692,
      },
      {
        id: "payakumbuh",
        name: "Kota Payakumbuh",
        latitude: -0.2167,
        longitude: 100.6333,
      },
      {
        id: "padangpanjang",
        name: "Kota Padang Panjang",
        latitude: -0.4667,
        longitude: 100.4167,
      },
      { id: "solok", name: "Kota Solok", latitude: -0.7833, longitude: 100.65 },
      {
        id: "sawahlunto",
        name: "Kota Sawahlunto",
        latitude: -0.6833,
        longitude: 100.7833,
      },
      {
        id: "pariaman",
        name: "Kota Pariaman",
        latitude: -0.6167,
        longitude: 100.1167,
      },
      { id: "agam", name: "Kab. Agam", latitude: -0.25, longitude: 100.3333 },
      {
        id: "limapuluhkota",
        name: "Kab. Lima Puluh Kota",
        latitude: -0.1667,
        longitude: 100.65,
      },
      {
        id: "pasaman",
        name: "Kab. Pasaman",
        latitude: 0.1333,
        longitude: 99.95,
      },
      {
        id: "pesisir-selatan",
        name: "Kab. Pesisir Selatan",
        latitude: -1.5667,
        longitude: 100.8333,
      },
      {
        id: "sijunjung",
        name: "Kab. Sijunjung",
        latitude: -0.7,
        longitude: 100.95,
      },
      {
        id: "tanah-datar",
        name: "Kab. Tanah Datar",
        latitude: -0.4667,
        longitude: 100.55,
      },
    ],
  },
  {
    id: "riau",
    name: "Riau",
    cities: [
      {
        id: "pekanbaru",
        name: "Kota Pekanbaru",
        latitude: 0.5071,
        longitude: 101.4478,
      },
      { id: "dumai", name: "Kota Dumai", latitude: 1.6667, longitude: 101.45 },
      {
        id: "bengkalis",
        name: "Kab. Bengkalis",
        latitude: 1.4833,
        longitude: 102.1333,
      },
      {
        id: "indragiri-hilir",
        name: "Kab. Indragiri Hilir",
        latitude: -0.3333,
        longitude: 103.1667,
      },
      {
        id: "indragiri-hulu",
        name: "Kab. Indragiri Hulu",
        latitude: -0.55,
        longitude: 102.35,
      },
      { id: "kampar", name: "Kab. Kampar", latitude: 0.3333, longitude: 101.2 },
      {
        id: "pelalawan",
        name: "Kab. Pelalawan",
        latitude: 0.4,
        longitude: 102.15,
      },
      {
        id: "rokan-hilir",
        name: "Kab. Rokan Hilir",
        latitude: 1.95,
        longitude: 100.8,
      },
      {
        id: "rokan-hulu",
        name: "Kab. Rokan Hulu",
        latitude: 0.8833,
        longitude: 100.4,
      },
      { id: "siak", name: "Kab. Siak", latitude: 1.1, longitude: 102.15 },
      {
        id: "kuantan-singingi",
        name: "Kab. Kuantan Singingi",
        latitude: -0.5333,
        longitude: 101.5333,
      },
    ],
  },
  {
    id: "kepri",
    name: "Kepulauan Riau",
    cities: [
      {
        id: "batam",
        name: "Kota Batam",
        latitude: 1.0456,
        longitude: 104.0305,
      },
      {
        id: "tanjungpinang",
        name: "Kota Tanjung Pinang",
        latitude: 0.9167,
        longitude: 104.45,
      },
      {
        id: "bintan",
        name: "Kab. Bintan",
        latitude: 1.0833,
        longitude: 104.5167,
      },
      {
        id: "karimun",
        name: "Kab. Karimun",
        latitude: 0.95,
        longitude: 103.4167,
      },
      {
        id: "natuna",
        name: "Kab. Natuna",
        latitude: 3.9333,
        longitude: 108.3833,
      },
      {
        id: "lingga",
        name: "Kab. Lingga",
        latitude: -0.2167,
        longitude: 104.5833,
      },
      {
        id: "kepulauan-anambas",
        name: "Kab. Kepulauan Anambas",
        latitude: 3.2167,
        longitude: 106.25,
      },
    ],
  },
  {
    id: "jambi",
    name: "Jambi",
    cities: [
      {
        id: "jambi",
        name: "Kota Jambi",
        latitude: -1.5833,
        longitude: 103.6167,
      },
      {
        id: "sungaipenuh",
        name: "Kota Sungai Penuh",
        latitude: -2.0833,
        longitude: 101.3833,
      },
      {
        id: "batanghari",
        name: "Kab. Batanghari",
        latitude: -1.6,
        longitude: 103.25,
      },
      {
        id: "bungo",
        name: "Kab. Bungo",
        latitude: -1.5167,
        longitude: 102.1167,
      },
      {
        id: "kerinci",
        name: "Kab. Kerinci",
        latitude: -2.0667,
        longitude: 101.4833,
      },
      {
        id: "merangin",
        name: "Kab. Merangin",
        latitude: -2.2833,
        longitude: 102.25,
      },
      {
        id: "muarojambi",
        name: "Kab. Muaro Jambi",
        latitude: -1.5333,
        longitude: 103.8833,
      },
      {
        id: "sarolangun",
        name: "Kab. Sarolangun",
        latitude: -2.3167,
        longitude: 102.85,
      },
      {
        id: "tanjungjabungbarat",
        name: "Kab. Tanjung Jabung Barat",
        latitude: -1.0833,
        longitude: 103.4667,
      },
      {
        id: "tanjungjabungtimur",
        name: "Kab. Tanjung Jabung Timur",
        latitude: -1.0667,
        longitude: 104.1167,
      },
      { id: "tebo", name: "Kab. Tebo", latitude: -1.4667, longitude: 102.3833 },
    ],
  },
  {
    id: "sumsel",
    name: "Sumatera Selatan",
    cities: [
      {
        id: "palembang",
        name: "Kota Palembang",
        latitude: -2.9761,
        longitude: 104.7754,
      },
      {
        id: "prabumulih",
        name: "Kota Prabumulih",
        latitude: -3.4333,
        longitude: 104.2333,
      },
      {
        id: "pagaralam",
        name: "Kota Pagar Alam",
        latitude: -4.0333,
        longitude: 103.25,
      },
      {
        id: "lubuklinggau",
        name: "Kota Lubuk Linggau",
        latitude: -3.2833,
        longitude: 102.85,
      },
      {
        id: "banyuasin",
        name: "Kab. Banyuasin",
        latitude: -2.55,
        longitude: 104.7,
      },
      {
        id: "empatlawang",
        name: "Kab. Empat Lawang",
        latitude: -3.7833,
        longitude: 103.2333,
      },
      {
        id: "lahat",
        name: "Kab. Lahat",
        latitude: -3.7833,
        longitude: 103.5333,
      },
      {
        id: "muaraenim",
        name: "Kab. Muara Enim",
        latitude: -3.75,
        longitude: 104.0833,
      },
      {
        id: "musirawas",
        name: "Kab. Musi Rawas",
        latitude: -3.1,
        longitude: 102.9833,
      },
      {
        id: "musibanyuasin",
        name: "Kab. Musi Banyuasin",
        latitude: -2.5833,
        longitude: 103.75,
      },
      {
        id: "ogankomeringulu",
        name: "Kab. Ogan Komering Ulu",
        latitude: -4.1167,
        longitude: 104.05,
      },
      {
        id: "oganilir",
        name: "Kab. Ogan Ilir",
        latitude: -3.2333,
        longitude: 104.6167,
      },
    ],
  },
  {
    id: "babel",
    name: "Bangka Belitung",
    cities: [
      {
        id: "pangkalpinang",
        name: "Kota Pangkal Pinang",
        latitude: -2.1167,
        longitude: 106.1167,
      },
      {
        id: "bangka",
        name: "Kab. Bangka",
        latitude: -2.0333,
        longitude: 105.95,
      },
      {
        id: "bangkabarat",
        name: "Kab. Bangka Barat",
        latitude: -2.0667,
        longitude: 105.2,
      },
      {
        id: "bangkaselatan",
        name: "Kab. Bangka Selatan",
        latitude: -2.85,
        longitude: 106.1167,
      },
      {
        id: "bangkatengah",
        name: "Kab. Bangka Tengah",
        latitude: -2.4167,
        longitude: 106.0333,
      },
      {
        id: "belitung",
        name: "Kab. Belitung",
        latitude: -2.85,
        longitude: 107.75,
      },
      {
        id: "belitungtimur",
        name: "Kab. Belitung Timur",
        latitude: -2.85,
        longitude: 108.0833,
      },
    ],
  },
  {
    id: "bengkulu",
    name: "Bengkulu",
    cities: [
      {
        id: "bengkulu",
        name: "Kota Bengkulu",
        latitude: -3.8004,
        longitude: 102.2655,
      },
      {
        id: "bengkuluselatan",
        name: "Kab. Bengkulu Selatan",
        latitude: -4.4333,
        longitude: 103.0167,
      },
      {
        id: "bengkulutengah",
        name: "Kab. Bengkulu Tengah",
        latitude: -3.7167,
        longitude: 102.2333,
      },
      {
        id: "bengkuluutara",
        name: "Kab. Bengkulu Utara",
        latitude: -3.45,
        longitude: 102.15,
      },
      { id: "kaur", name: "Kab. Kaur", latitude: -4.5, longitude: 103.3833 },
      {
        id: "kepahiang",
        name: "Kab. Kepahiang",
        latitude: -3.6167,
        longitude: 102.5667,
      },
      {
        id: "lebong",
        name: "Kab. Lebong",
        latitude: -3.1833,
        longitude: 102.3833,
      },
      {
        id: "mukomuko",
        name: "Kab. Muko Muko",
        latitude: -2.5833,
        longitude: 101.1167,
      },
      {
        id: "rejanglebong",
        name: "Kab. Rejang Lebong",
        latitude: -3.45,
        longitude: 102.65,
      },
      {
        id: "seluma",
        name: "Kab. Seluma",
        latitude: -4.0,
        longitude: 102.5333,
      },
    ],
  },
  {
    id: "lampung",
    name: "Lampung",
    cities: [
      {
        id: "bandarlampung",
        name: "Kota Bandar Lampung",
        latitude: -5.45,
        longitude: 105.2667,
      },
      { id: "metro", name: "Kota Metro", latitude: -5.1167, longitude: 105.3 },
      {
        id: "lampungbarat",
        name: "Kab. Lampung Barat",
        latitude: -5.0333,
        longitude: 104.0333,
      },
      {
        id: "lampungselatan",
        name: "Kab. Lampung Selatan",
        latitude: -5.6167,
        longitude: 105.5833,
      },
      {
        id: "lampungtengah",
        name: "Kab. Lampung Tengah",
        latitude: -4.8167,
        longitude: 105.2833,
      },
      {
        id: "lampungtimur",
        name: "Kab. Lampung Timur",
        latitude: -5.1,
        longitude: 105.75,
      },
      {
        id: "lampungutara",
        name: "Kab. Lampung Utara",
        latitude: -4.8333,
        longitude: 104.75,
      },
      {
        id: "mesuji",
        name: "Kab. Mesuji",
        latitude: -4.0833,
        longitude: 105.4667,
      },
      {
        id: "pesawaran",
        name: "Kab. Pesawaran",
        latitude: -5.4167,
        longitude: 105.05,
      },
      {
        id: "pesisir-barat",
        name: "Kab. Pesisir Barat",
        latitude: -5.2167,
        longitude: 103.95,
      },
      {
        id: "pringsewu",
        name: "Kab. Pringsewu",
        latitude: -5.35,
        longitude: 104.9833,
      },
      {
        id: "tanggamus",
        name: "Kab. Tanggamus",
        latitude: -5.4,
        longitude: 104.6333,
      },
      {
        id: "tulangbawang",
        name: "Kab. Tulang Bawang",
        latitude: -4.3167,
        longitude: 105.45,
      },
      {
        id: "waykanan",
        name: "Kab. Way Kanan",
        latitude: -4.4833,
        longitude: 104.4833,
      },
    ],
  },
  {
    id: "jakarta",
    name: "DKI Jakarta",
    cities: [
      {
        id: "jakarta-pusat",
        name: "Jakarta Pusat",
        latitude: -6.1862,
        longitude: 106.834,
      },
      {
        id: "jakarta-utara",
        name: "Jakarta Utara",
        latitude: -6.1384,
        longitude: 106.8633,
      },
      {
        id: "jakarta-barat",
        name: "Jakarta Barat",
        latitude: -6.1673,
        longitude: 106.7637,
      },
      {
        id: "jakarta-selatan",
        name: "Jakarta Selatan",
        latitude: -6.2615,
        longitude: 106.8106,
      },
      {
        id: "jakarta-timur",
        name: "Jakarta Timur",
        latitude: -6.225,
        longitude: 106.9004,
      },
      {
        id: "kepulauan-seribu",
        name: "Kab. Kepulauan Seribu",
        latitude: -5.6167,
        longitude: 106.5667,
      },
    ],
  },
  {
    id: "jabar",
    name: "Jawa Barat",
    cities: [
      {
        id: "bandung",
        name: "Kota Bandung",
        latitude: -6.9175,
        longitude: 107.6191,
      },
      {
        id: "bekasi",
        name: "Kota Bekasi",
        latitude: -6.2349,
        longitude: 106.9896,
      },
      {
        id: "bogor",
        name: "Kota Bogor",
        latitude: -6.5944,
        longitude: 106.7892,
      },
      {
        id: "cimahi",
        name: "Kota Cimahi",
        latitude: -6.8667,
        longitude: 107.5333,
      },
      {
        id: "cirebon",
        name: "Kota Cirebon",
        latitude: -6.7063,
        longitude: 108.557,
      },
      {
        id: "depok",
        name: "Kota Depok",
        latitude: -6.4025,
        longitude: 106.7942,
      },
      {
        id: "sukabumi",
        name: "Kota Sukabumi",
        latitude: -6.9167,
        longitude: 106.9167,
      },
      {
        id: "tasikmalaya",
        name: "Kota Tasikmalaya",
        latitude: -7.3274,
        longitude: 108.2207,
      },
      {
        id: "banjar",
        name: "Kota Banjar",
        latitude: -7.3667,
        longitude: 108.5333,
      },
      {
        id: "kab-bandung",
        name: "Kab. Bandung",
        latitude: -7.0333,
        longitude: 107.5167,
      },
      {
        id: "kab-bandung-barat",
        name: "Kab. Bandung Barat",
        latitude: -6.85,
        longitude: 107.4333,
      },
      {
        id: "kab-bekasi",
        name: "Kab. Bekasi",
        latitude: -6.3,
        longitude: 107.1333,
      },
      {
        id: "kab-bogor",
        name: "Kab. Bogor",
        latitude: -6.65,
        longitude: 106.8333,
      },
      {
        id: "ciamis",
        name: "Kab. Ciamis",
        latitude: -7.3333,
        longitude: 108.35,
      },
      {
        id: "cianjur",
        name: "Kab. Cianjur",
        latitude: -6.8167,
        longitude: 107.15,
      },
      {
        id: "kab-cirebon",
        name: "Kab. Cirebon",
        latitude: -6.7167,
        longitude: 108.5667,
      },
      { id: "garut", name: "Kab. Garut", latitude: -7.2167, longitude: 107.9 },
      {
        id: "indramayu",
        name: "Kab. Indramayu",
        latitude: -6.3333,
        longitude: 108.3167,
      },
      {
        id: "karawang",
        name: "Kab. Karawang",
        latitude: -6.3,
        longitude: 107.3,
      },
      {
        id: "kuningan",
        name: "Kab. Kuningan",
        latitude: -6.9833,
        longitude: 108.4667,
      },
      {
        id: "majalengka",
        name: "Kab. Majalengka",
        latitude: -6.8333,
        longitude: 108.2333,
      },
      {
        id: "pangandaran",
        name: "Kab. Pangandaran",
        latitude: -7.6833,
        longitude: 108.6333,
      },
      {
        id: "purwakarta",
        name: "Kab. Purwakarta",
        latitude: -6.5333,
        longitude: 107.4333,
      },
      {
        id: "subang",
        name: "Kab. Subang",
        latitude: -6.5667,
        longitude: 107.75,
      },
      {
        id: "kab-sukabumi",
        name: "Kab. Sukabumi",
        latitude: -7.0,
        longitude: 106.6667,
      },
      {
        id: "sumedang",
        name: "Kab. Sumedang",
        latitude: -6.8333,
        longitude: 107.9167,
      },
      {
        id: "kab-tasikmalaya",
        name: "Kab. Tasikmalaya",
        latitude: -7.3667,
        longitude: 108.1333,
      },
    ],
  },
  {
    id: "banten",
    name: "Banten",
    cities: [
      {
        id: "serang",
        name: "Kota Serang",
        latitude: -6.1167,
        longitude: 106.15,
      },
      {
        id: "cilegon",
        name: "Kota Cilegon",
        latitude: -6.0167,
        longitude: 106.05,
      },
      {
        id: "tangerang",
        name: "Kota Tangerang",
        latitude: -6.1783,
        longitude: 106.6319,
      },
      {
        id: "tangerang-selatan",
        name: "Kota Tangerang Selatan",
        latitude: -6.2833,
        longitude: 106.7167,
      },
      { id: "lebak", name: "Kab. Lebak", latitude: -6.5667, longitude: 106.25 },
      {
        id: "pandeglang",
        name: "Kab. Pandeglang",
        latitude: -6.55,
        longitude: 105.95,
      },
      {
        id: "kab-serang",
        name: "Kab. Serang",
        latitude: -6.25,
        longitude: 106.0833,
      },
      {
        id: "kab-tangerang",
        name: "Kab. Tangerang",
        latitude: -6.25,
        longitude: 106.55,
      },
    ],
  },
  {
    id: "jateng",
    name: "Jawa Tengah",
    cities: [
      {
        id: "semarang",
        name: "Kota Semarang",
        latitude: -6.9666,
        longitude: 110.4196,
      },
      {
        id: "magelang",
        name: "Kota Magelang",
        latitude: -7.4797,
        longitude: 110.2177,
      },
      {
        id: "pekalongan",
        name: "Kota Pekalongan",
        latitude: -6.8885,
        longitude: 109.6753,
      },
      {
        id: "salatiga",
        name: "Kota Salatiga",
        latitude: -7.3167,
        longitude: 110.4833,
      },
      {
        id: "surakarta",
        name: "Kota Surakarta (Solo)",
        latitude: -7.5755,
        longitude: 110.8243,
      },
      {
        id: "tegal",
        name: "Kota Tegal",
        latitude: -6.8797,
        longitude: 109.1256,
      },
      {
        id: "banjarnegara",
        name: "Kab. Banjarnegara",
        latitude: -7.3833,
        longitude: 109.6833,
      },
      {
        id: "banyumas",
        name: "Kab. Banyumas",
        latitude: -7.4167,
        longitude: 109.2333,
      },
      {
        id: "batang",
        name: "Kab. Batang",
        latitude: -6.9167,
        longitude: 109.7167,
      },
      {
        id: "blora",
        name: "Kab. Blora",
        latitude: -6.9667,
        longitude: 111.4167,
      },
      {
        id: "boyolali",
        name: "Kab. Boyolali",
        latitude: -7.5333,
        longitude: 110.6,
      },
      {
        id: "brebes",
        name: "Kab. Brebes",
        latitude: -6.8833,
        longitude: 109.0333,
      },
      {
        id: "cilacap",
        name: "Kab. Cilacap",
        latitude: -7.7333,
        longitude: 109.0,
      },
      {
        id: "demak",
        name: "Kab. Demak",
        latitude: -6.8833,
        longitude: 110.6333,
      },
      {
        id: "grobogan",
        name: "Kab. Grobogan",
        latitude: -7.15,
        longitude: 110.8667,
      },
      {
        id: "jepara",
        name: "Kab. Jepara",
        latitude: -6.5833,
        longitude: 110.6833,
      },
      {
        id: "karanganyar",
        name: "Kab. Karanganyar",
        latitude: -7.5833,
        longitude: 110.95,
      },
      {
        id: "kebumen",
        name: "Kab. Kebumen",
        latitude: -7.6667,
        longitude: 109.65,
      },
      {
        id: "kendal",
        name: "Kab. Kendal",
        latitude: -6.9167,
        longitude: 110.2,
      },
      {
        id: "klaten",
        name: "Kab. Klaten",
        latitude: -7.7167,
        longitude: 110.6,
      },
      { id: "kudus", name: "Kab. Kudus", latitude: -6.8, longitude: 110.85 },
      {
        id: "kab-magelang",
        name: "Kab. Magelang",
        latitude: -7.4667,
        longitude: 110.2167,
      },
      {
        id: "kab-pekalongan",
        name: "Kab. Pekalongan",
        latitude: -7.0667,
        longitude: 109.65,
      },
      {
        id: "pemalang",
        name: "Kab. Pemalang",
        latitude: -6.9,
        longitude: 109.3833,
      },
      {
        id: "purbalingga",
        name: "Kab. Purbalingga",
        latitude: -7.3833,
        longitude: 109.3667,
      },
      {
        id: "purworejo",
        name: "Kab. Purworejo",
        latitude: -7.7167,
        longitude: 110.0167,
      },
      {
        id: "rembang",
        name: "Kab. Rembang",
        latitude: -6.7167,
        longitude: 111.35,
      },
      {
        id: "kab-semarang",
        name: "Kab. Semarang",
        latitude: -7.15,
        longitude: 110.4,
      },
      {
        id: "sragen",
        name: "Kab. Sragen",
        latitude: -7.4167,
        longitude: 111.0167,
      },
      {
        id: "sukoharjo",
        name: "Kab. Sukoharjo",
        latitude: -7.6667,
        longitude: 110.8333,
      },
      {
        id: "kab-tegal",
        name: "Kab. Tegal",
        latitude: -7.05,
        longitude: 109.15,
      },
      {
        id: "temanggung",
        name: "Kab. Temanggung",
        latitude: -7.3,
        longitude: 110.1833,
      },
      {
        id: "wonogiri",
        name: "Kab. Wonogiri",
        latitude: -7.8333,
        longitude: 110.9167,
      },
      {
        id: "wonosobo",
        name: "Kab. Wonosobo",
        latitude: -7.3667,
        longitude: 109.9,
      },
      { id: "pati", name: "Kab. Pati", latitude: -6.75, longitude: 111.05 },
    ],
  },
  {
    id: "diy",
    name: "DI Yogyakarta",
    cities: [
      {
        id: "yogyakarta",
        name: "Kota Yogyakarta",
        latitude: -7.7956,
        longitude: 110.3695,
      },
      {
        id: "bantul",
        name: "Kab. Bantul",
        latitude: -7.8833,
        longitude: 110.3333,
      },
      {
        id: "gunungkidul",
        name: "Kab. Gunung Kidul",
        latitude: -7.9833,
        longitude: 110.6167,
      },
      {
        id: "kulonprogo",
        name: "Kab. Kulon Progo",
        latitude: -7.8333,
        longitude: 110.1667,
      },
      {
        id: "sleman",
        name: "Kab. Sleman",
        latitude: -7.7167,
        longitude: 110.35,
      },
    ],
  },
  {
    id: "jatim",
    name: "Jawa Timur",
    cities: [
      {
        id: "surabaya",
        name: "Kota Surabaya",
        latitude: -7.2575,
        longitude: 112.7521,
      },
      {
        id: "malang",
        name: "Kota Malang",
        latitude: -7.9797,
        longitude: 112.6304,
      },
      { id: "batu", name: "Kota Batu", latitude: -7.8833, longitude: 112.5333 },
      {
        id: "blitar",
        name: "Kota Blitar",
        latitude: -8.0956,
        longitude: 112.1609,
      },
      {
        id: "kediri",
        name: "Kota Kediri",
        latitude: -7.8167,
        longitude: 112.0167,
      },
      {
        id: "madiun",
        name: "Kota Madiun",
        latitude: -7.6298,
        longitude: 111.53,
      },
      {
        id: "mojokerto",
        name: "Kota Mojokerto",
        latitude: -7.4667,
        longitude: 112.4333,
      },
      {
        id: "pasuruan",
        name: "Kota Pasuruan",
        latitude: -7.6333,
        longitude: 112.9,
      },
      {
        id: "probolinggo",
        name: "Kota Probolinggo",
        latitude: -7.7543,
        longitude: 113.2159,
      },
      {
        id: "kota-banyuwangi",
        name: "Kab. Banyuwangi",
        latitude: -8.2167,
        longitude: 114.35,
      },
      {
        id: "kab-blitar",
        name: "Kab. Blitar",
        latitude: -8.15,
        longitude: 112.2,
      },
      {
        id: "bojonegoro",
        name: "Kab. Bojonegoro",
        latitude: -7.15,
        longitude: 111.8833,
      },
      {
        id: "bondowoso",
        name: "Kab. Bondowoso",
        latitude: -7.9167,
        longitude: 113.8167,
      },
      {
        id: "gresik",
        name: "Kab. Gresik",
        latitude: -7.1667,
        longitude: 112.65,
      },
      {
        id: "jember",
        name: "Kab. Jember",
        latitude: -8.1667,
        longitude: 113.7,
      },
      {
        id: "jombang",
        name: "Kab. Jombang",
        latitude: -7.55,
        longitude: 112.2333,
      },
      {
        id: "kab-kediri",
        name: "Kab. Kediri",
        latitude: -7.8333,
        longitude: 112.0,
      },
      {
        id: "lamongan",
        name: "Kab. Lamongan",
        latitude: -7.1167,
        longitude: 112.4167,
      },
      {
        id: "lumajang",
        name: "Kab. Lumajang",
        latitude: -8.1333,
        longitude: 113.2333,
      },
      {
        id: "kab-madiun",
        name: "Kab. Madiun",
        latitude: -7.5333,
        longitude: 111.5333,
      },
      {
        id: "magetan",
        name: "Kab. Magetan",
        latitude: -7.65,
        longitude: 111.35,
      },
      {
        id: "kab-malang",
        name: "Kab. Malang",
        latitude: -8.0667,
        longitude: 112.6,
      },
      {
        id: "kab-mojokerto",
        name: "Kab. Mojokerto",
        latitude: -7.55,
        longitude: 112.5333,
      },
      { id: "nganjuk", name: "Kab. Nganjuk", latitude: -7.6, longitude: 111.9 },
      { id: "ngawi", name: "Kab. Ngawi", latitude: -7.4, longitude: 111.45 },
      {
        id: "pacitan",
        name: "Kab. Pacitan",
        latitude: -8.1833,
        longitude: 111.1,
      },
      {
        id: "pamekasan",
        name: "Kab. Pamekasan",
        latitude: -7.15,
        longitude: 113.4833,
      },
      {
        id: "kab-pasuruan",
        name: "Kab. Pasuruan",
        latitude: -7.7167,
        longitude: 112.9,
      },
      {
        id: "ponorogo",
        name: "Kab. Ponorogo",
        latitude: -7.8667,
        longitude: 111.4667,
      },
      {
        id: "kab-probolinggo",
        name: "Kab. Probolinggo",
        latitude: -7.9,
        longitude: 113.2667,
      },
      {
        id: "sampang",
        name: "Kab. Sampang",
        latitude: -7.1833,
        longitude: 113.25,
      },
      {
        id: "sidoarjo",
        name: "Kab. Sidoarjo",
        latitude: -7.45,
        longitude: 112.7167,
      },
      {
        id: "situbondo",
        name: "Kab. Situbondo",
        latitude: -7.7,
        longitude: 114.0167,
      },
      {
        id: "sumenep",
        name: "Kab. Sumenep",
        latitude: -7.0167,
        longitude: 113.8667,
      },
      {
        id: "trenggalek",
        name: "Kab. Trenggalek",
        latitude: -8.05,
        longitude: 111.7,
      },
      { id: "tuban", name: "Kab. Tuban", latitude: -6.9, longitude: 112.05 },
      {
        id: "tulungagung",
        name: "Kab. Tulungagung",
        latitude: -8.0667,
        longitude: 111.9,
      },
    ],
  },
  {
    id: "bali",
    name: "Bali",
    cities: [
      {
        id: "denpasar",
        name: "Kota Denpasar",
        latitude: -8.65,
        longitude: 115.2167,
      },
      {
        id: "badung",
        name: "Kab. Badung",
        latitude: -8.5833,
        longitude: 115.1833,
      },
      { id: "bangli", name: "Kab. Bangli", latitude: -8.45, longitude: 115.35 },
      {
        id: "buleleng",
        name: "Kab. Buleleng",
        latitude: -8.1167,
        longitude: 115.0833,
      },
      {
        id: "gianyar",
        name: "Kab. Gianyar",
        latitude: -8.5333,
        longitude: 115.3167,
      },
      {
        id: "jembrana",
        name: "Kab. Jembrana",
        latitude: -8.35,
        longitude: 114.6333,
      },
      {
        id: "karangasem",
        name: "Kab. Karangasem",
        latitude: -8.45,
        longitude: 115.6167,
      },
      {
        id: "klungkung",
        name: "Kab. Klungkung",
        latitude: -8.5333,
        longitude: 115.4167,
      },
      {
        id: "tabanan",
        name: "Kab. Tabanan",
        latitude: -8.55,
        longitude: 115.1,
      },
    ],
  },
  {
    id: "ntb",
    name: "Nusa Tenggara Barat",
    cities: [
      {
        id: "mataram",
        name: "Kota Mataram",
        latitude: -8.5833,
        longitude: 116.1167,
      },
      { id: "bima", name: "Kota Bima", latitude: -8.45, longitude: 118.7167 },
      { id: "dompu", name: "Kab. Dompu", latitude: -8.5333, longitude: 118.45 },
      {
        id: "kab-bima",
        name: "Kab. Bima",
        latitude: -8.4333,
        longitude: 118.9167,
      },
      {
        id: "lombok-barat",
        name: "Kab. Lombok Barat",
        latitude: -8.6167,
        longitude: 116.0833,
      },
      {
        id: "lombok-tengah",
        name: "Kab. Lombok Tengah",
        latitude: -8.7167,
        longitude: 116.2667,
      },
      {
        id: "lombok-timur",
        name: "Kab. Lombok Timur",
        latitude: -8.5,
        longitude: 116.5333,
      },
      {
        id: "lombok-utara",
        name: "Kab. Lombok Utara",
        latitude: -8.4,
        longitude: 116.4,
      },
      {
        id: "sumbawa",
        name: "Kab. Sumbawa",
        latitude: -8.5,
        longitude: 117.4167,
      },
      {
        id: "sumbawa-barat",
        name: "Kab. Sumbawa Barat",
        latitude: -8.7833,
        longitude: 116.8833,
      },
    ],
  },
  {
    id: "ntt",
    name: "Nusa Tenggara Timur",
    cities: [
      {
        id: "kupang",
        name: "Kota Kupang",
        latitude: -10.1667,
        longitude: 123.5833,
      },
      { id: "alor", name: "Kab. Alor", latitude: -8.25, longitude: 124.75 },
      { id: "belu", name: "Kab. Belu", latitude: -9.1333, longitude: 124.8833 },
      { id: "ende", name: "Kab. Ende", latitude: -8.85, longitude: 121.65 },
      {
        id: "flores-timur",
        name: "Kab. Flores Timur",
        latitude: -8.3333,
        longitude: 122.8833,
      },
      {
        id: "kab-kupang",
        name: "Kab. Kupang",
        latitude: -10.1667,
        longitude: 123.5833,
      },
      {
        id: "lembata",
        name: "Kab. Lembata",
        latitude: -8.3667,
        longitude: 123.5167,
      },
      { id: "malaka", name: "Kab. Malaka", latitude: -9.55, longitude: 124.9 },
      {
        id: "manggarai",
        name: "Kab. Manggarai",
        latitude: -8.6167,
        longitude: 120.4833,
      },
      {
        id: "manggarai-barat",
        name: "Kab. Manggarai Barat",
        latitude: -8.5333,
        longitude: 119.9,
      },
      {
        id: "manggarai-timur",
        name: "Kab. Manggarai Timur",
        latitude: -8.6333,
        longitude: 120.8833,
      },
      {
        id: "nagekeo",
        name: "Kab. Nagekeo",
        latitude: -8.7833,
        longitude: 121.1333,
      },
      { id: "ngada", name: "Kab. Ngada", latitude: -8.7, longitude: 120.95 },
      {
        id: "rote-ndao",
        name: "Kab. Rote Ndao",
        latitude: -10.7333,
        longitude: 123.0833,
      },
      {
        id: "sabu-raijua",
        name: "Kab. Sabu Raijua",
        latitude: -10.5,
        longitude: 121.85,
      },
      {
        id: "sikka",
        name: "Kab. Sikka",
        latitude: -8.6167,
        longitude: 122.2333,
      },
      {
        id: "sumba-barat",
        name: "Kab. Sumba Barat",
        latitude: -9.65,
        longitude: 119.4,
      },
      {
        id: "sumba-barat-daya",
        name: "Kab. Sumba Barat Daya",
        latitude: -9.6167,
        longitude: 119.05,
      },
      {
        id: "sumba-tengah",
        name: "Kab. Sumba Tengah",
        latitude: -9.5333,
        longitude: 119.5833,
      },
      {
        id: "sumba-timur",
        name: "Kab. Sumba Timur",
        latitude: -9.95,
        longitude: 120.25,
      },
      {
        id: "timor-tengah-selatan",
        name: "Kab. Timor Tengah Selatan",
        latitude: -9.7667,
        longitude: 124.2333,
      },
      {
        id: "timor-tengah-utara",
        name: "Kab. Timor Tengah Utara",
        latitude: -9.45,
        longitude: 124.6667,
      },
    ],
  },
  {
    id: "kalbar",
    name: "Kalimantan Barat",
    cities: [
      {
        id: "pontianak",
        name: "Kota Pontianak",
        latitude: -0.0226,
        longitude: 109.3431,
      },
      {
        id: "singkawang",
        name: "Kota Singkawang",
        latitude: 0.9,
        longitude: 108.9833,
      },
      {
        id: "bengkayang",
        name: "Kab. Bengkayang",
        latitude: 0.8167,
        longitude: 109.5667,
      },
      {
        id: "kapuas-hulu",
        name: "Kab. Kapuas Hulu",
        latitude: 0.95,
        longitude: 112.9333,
      },
      {
        id: "kayong-utara",
        name: "Kab. Kayong Utara",
        latitude: -1.0833,
        longitude: 109.95,
      },
      {
        id: "ketapang",
        name: "Kab. Ketapang",
        latitude: -1.8333,
        longitude: 109.9833,
      },
      {
        id: "kubu-raya",
        name: "Kab. Kubu Raya",
        latitude: -0.1667,
        longitude: 109.3833,
      },
      {
        id: "landak",
        name: "Kab. Landak",
        latitude: 0.3667,
        longitude: 109.85,
      },
      {
        id: "melawi",
        name: "Kab. Melawi",
        latitude: -0.6167,
        longitude: 111.3667,
      },
      {
        id: "mempawah",
        name: "Kab. Mempawah",
        latitude: 0.35,
        longitude: 109.1333,
      },
      {
        id: "sambas",
        name: "Kab. Sambas",
        latitude: 1.35,
        longitude: 109.3167,
      },
      {
        id: "sanggau",
        name: "Kab. Sanggau",
        latitude: 0.1333,
        longitude: 110.5833,
      },
      {
        id: "sekadau",
        name: "Kab. Sekadau",
        latitude: -0.05,
        longitude: 110.9167,
      },
      {
        id: "sintang",
        name: "Kab. Sintang",
        latitude: 0.0667,
        longitude: 111.4833,
      },
    ],
  },
  {
    id: "kalteng",
    name: "Kalimantan Tengah",
    cities: [
      {
        id: "palangkaraya",
        name: "Kota Palangka Raya",
        latitude: -2.2136,
        longitude: 113.9108,
      },
      {
        id: "barito-selatan",
        name: "Kab. Barito Selatan",
        latitude: -2.3667,
        longitude: 114.8833,
      },
      {
        id: "barito-timur",
        name: "Kab. Barito Timur",
        latitude: -1.9333,
        longitude: 115.2,
      },
      {
        id: "barito-utara",
        name: "Kab. Barito Utara",
        latitude: -0.8833,
        longitude: 115.2,
      },
      {
        id: "gunung-mas",
        name: "Kab. Gunung Mas",
        latitude: -1.1667,
        longitude: 113.55,
      },
      {
        id: "kapuas",
        name: "Kab. Kapuas",
        latitude: -2.9333,
        longitude: 114.2,
      },
      {
        id: "katingan",
        name: "Kab. Katingan",
        latitude: -1.8667,
        longitude: 113.4167,
      },
      {
        id: "kotawaringin-barat",
        name: "Kab. Kotawaringin Barat",
        latitude: -2.6833,
        longitude: 111.6167,
      },
      {
        id: "kotawaringin-timur",
        name: "Kab. Kotawaringin Timur",
        latitude: -2.5333,
        longitude: 112.95,
      },
      {
        id: "lamandau",
        name: "Kab. Lamandau",
        latitude: -2.3667,
        longitude: 111.2,
      },
      {
        id: "murung-raya",
        name: "Kab. Murung Raya",
        latitude: -0.4,
        longitude: 114.35,
      },
      {
        id: "pulang-pisau",
        name: "Kab. Pulang Pisau",
        latitude: -2.75,
        longitude: 114.0833,
      },
      {
        id: "seruyan",
        name: "Kab. Seruyan",
        latitude: -3.2,
        longitude: 112.3833,
      },
      {
        id: "sukamara",
        name: "Kab. Sukamara",
        latitude: -2.85,
        longitude: 111.2167,
      },
    ],
  },
  {
    id: "kalsel",
    name: "Kalimantan Selatan",
    cities: [
      {
        id: "banjarmasin",
        name: "Kota Banjarmasin",
        latitude: -3.3194,
        longitude: 114.59,
      },
      {
        id: "banjarbaru",
        name: "Kota Banjarbaru",
        latitude: -3.45,
        longitude: 114.8167,
      },
      {
        id: "balangan",
        name: "Kab. Balangan",
        latitude: -2.3,
        longitude: 115.6,
      },
      {
        id: "banjar",
        name: "Kab. Banjar",
        latitude: -3.4167,
        longitude: 115.0,
      },
      {
        id: "barito-kuala",
        name: "Kab. Barito Kuala",
        latitude: -3.0833,
        longitude: 114.6167,
      },
      {
        id: "hulu-sungai-selatan",
        name: "Kab. Hulu Sungai Selatan",
        latitude: -2.7833,
        longitude: 115.2,
      },
      {
        id: "hulu-sungai-tengah",
        name: "Kab. Hulu Sungai Tengah",
        latitude: -2.6,
        longitude: 115.3667,
      },
      {
        id: "hulu-sungai-utara",
        name: "Kab. Hulu Sungai Utara",
        latitude: -2.45,
        longitude: 115.35,
      },
      {
        id: "kotabaru",
        name: "Kab. Kotabaru",
        latitude: -3.2833,
        longitude: 116.2333,
      },
      {
        id: "tabalong",
        name: "Kab. Tabalong",
        latitude: -2.25,
        longitude: 115.65,
      },
      {
        id: "tanah-bumbu",
        name: "Kab. Tanah Bumbu",
        latitude: -3.4833,
        longitude: 115.7167,
      },
      {
        id: "tanah-laut",
        name: "Kab. Tanah Laut",
        latitude: -3.8,
        longitude: 114.8333,
      },
      { id: "tapin", name: "Kab. Tapin", latitude: -2.95, longitude: 115.0333 },
    ],
  },
  {
    id: "kaltim",
    name: "Kalimantan Timur",
    cities: [
      {
        id: "samarinda",
        name: "Kota Samarinda",
        latitude: -0.4948,
        longitude: 117.1436,
      },
      {
        id: "balikpapan",
        name: "Kota Balikpapan",
        latitude: -1.2379,
        longitude: 116.8529,
      },
      {
        id: "bontang",
        name: "Kota Bontang",
        latitude: 0.1333,
        longitude: 117.4833,
      },
      { id: "berau", name: "Kab. Berau", latitude: 2.15, longitude: 117.4833 },
      {
        id: "kutai-barat",
        name: "Kab. Kutai Barat",
        latitude: 0.0333,
        longitude: 115.7667,
      },
      {
        id: "kutai-kartanegara",
        name: "Kab. Kutai Kartanegara",
        latitude: -0.45,
        longitude: 116.9833,
      },
      {
        id: "kutai-timur",
        name: "Kab. Kutai Timur",
        latitude: 0.5333,
        longitude: 117.55,
      },
      {
        id: "mahakam-ulu",
        name: "Kab. Mahakam Ulu",
        latitude: 0.7167,
        longitude: 115.1667,
      },
      {
        id: "paser",
        name: "Kab. Paser",
        latitude: -1.9833,
        longitude: 116.0333,
      },
      {
        id: "penajam-paser-utara",
        name: "Kab. Penajam Paser Utara",
        latitude: -1.2333,
        longitude: 116.5167,
      },
    ],
  },
  {
    id: "kaltara",
    name: "Kalimantan Utara",
    cities: [
      {
        id: "tarakan",
        name: "Kota Tarakan",
        latitude: 3.3,
        longitude: 117.6333,
      },
      {
        id: "bulungan",
        name: "Kab. Bulungan",
        latitude: 2.8833,
        longitude: 117.3667,
      },
      {
        id: "malinau",
        name: "Kab. Malinau",
        latitude: 3.5833,
        longitude: 116.6333,
      },
      {
        id: "nunukan",
        name: "Kab. Nunukan",
        latitude: 4.1333,
        longitude: 117.6667,
      },
      {
        id: "tana-tidung",
        name: "Kab. Tana Tidung",
        latitude: 3.2667,
        longitude: 117.0833,
      },
    ],
  },
  {
    id: "sulut",
    name: "Sulawesi Utara",
    cities: [
      {
        id: "manado",
        name: "Kota Manado",
        latitude: 1.4748,
        longitude: 124.8421,
      },
      {
        id: "bitung",
        name: "Kota Bitung",
        latitude: 1.45,
        longitude: 125.1833,
      },
      {
        id: "tomohon",
        name: "Kota Tomohon",
        latitude: 1.35,
        longitude: 124.8333,
      },
      {
        id: "kotamobagu",
        name: "Kota Kotamobagu",
        latitude: 0.7167,
        longitude: 124.3167,
      },
      {
        id: "bolaang-mongondow",
        name: "Kab. Bolaang Mongondow",
        latitude: 0.75,
        longitude: 123.9333,
      },
      {
        id: "bolaang-mongondow-selatan",
        name: "Kab. Bolaang Mongondow Selatan",
        latitude: 0.5333,
        longitude: 124.0333,
      },
      {
        id: "bolaang-mongondow-timur",
        name: "Kab. Bolaang Mongondow Timur",
        latitude: 0.7333,
        longitude: 124.5667,
      },
      {
        id: "bolaang-mongondow-utara",
        name: "Kab. Bolaang Mongondow Utara",
        latitude: 0.9167,
        longitude: 123.65,
      },
      {
        id: "kepulauan-sangihe",
        name: "Kab. Kepulauan Sangihe",
        latitude: 3.6,
        longitude: 125.55,
      },
      {
        id: "kepulauan-siau",
        name: "Kab. Kepulauan Siau Tagulandang Biaro",
        latitude: 2.8167,
        longitude: 125.4333,
      },
      {
        id: "kepulauan-talaud",
        name: "Kab. Kepulauan Talaud",
        latitude: 4.0833,
        longitude: 126.6833,
      },
      {
        id: "minahasa",
        name: "Kab. Minahasa",
        latitude: 1.3,
        longitude: 124.8667,
      },
      {
        id: "minahasa-selatan",
        name: "Kab. Minahasa Selatan",
        latitude: 1.1333,
        longitude: 124.5167,
      },
      {
        id: "minahasa-tenggara",
        name: "Kab. Minahasa Tenggara",
        latitude: 0.9833,
        longitude: 124.8,
      },
      {
        id: "minahasa-utara",
        name: "Kab. Minahasa Utara",
        latitude: 1.4833,
        longitude: 125.05,
      },
    ],
  },
  {
    id: "gorontalo",
    name: "Gorontalo",
    cities: [
      {
        id: "gorontalo",
        name: "Kota Gorontalo",
        latitude: 0.5435,
        longitude: 123.0568,
      },
      {
        id: "bone-bolango",
        name: "Kab. Bone Bolango",
        latitude: 0.55,
        longitude: 123.25,
      },
      {
        id: "boalemo",
        name: "Kab. Boalemo",
        latitude: 0.65,
        longitude: 122.1333,
      },
      {
        id: "gorontalo-utara",
        name: "Kab. Gorontalo Utara",
        latitude: 0.8667,
        longitude: 122.6667,
      },
      {
        id: "kab-gorontalo",
        name: "Kab. Gorontalo",
        latitude: 0.6,
        longitude: 122.8167,
      },
      {
        id: "pohuwato",
        name: "Kab. Pohuwato",
        latitude: 0.65,
        longitude: 121.5667,
      },
    ],
  },
  {
    id: "sulteng",
    name: "Sulawesi Tengah",
    cities: [
      { id: "palu", name: "Kota Palu", latitude: -0.8917, longitude: 119.8707 },
      {
        id: "banggai",
        name: "Kab. Banggai",
        latitude: -1.5667,
        longitude: 123.05,
      },
      {
        id: "banggai-kepulauan",
        name: "Kab. Banggai Kepulauan",
        latitude: -1.65,
        longitude: 123.4833,
      },
      {
        id: "banggai-laut",
        name: "Kab. Banggai Laut",
        latitude: -1.8333,
        longitude: 123.3833,
      },
      { id: "buol", name: "Kab. Buol", latitude: 1.05, longitude: 121.4333 },
      {
        id: "donggala",
        name: "Kab. Donggala",
        latitude: -0.6833,
        longitude: 119.75,
      },
      {
        id: "morowali",
        name: "Kab. Morowali",
        latitude: -2.05,
        longitude: 121.75,
      },
      {
        id: "morowali-utara",
        name: "Kab. Morowali Utara",
        latitude: -1.65,
        longitude: 121.4167,
      },
      {
        id: "parigi-moutong",
        name: "Kab. Parigi Moutong",
        latitude: -0.4833,
        longitude: 120.1333,
      },
      { id: "poso", name: "Kab. Poso", latitude: -1.75, longitude: 120.7333 },
      { id: "sigi", name: "Kab. Sigi", latitude: -1.3167, longitude: 119.8667 },
      {
        id: "tojo-una-una",
        name: "Kab. Tojo Una-Una",
        latitude: -1.2333,
        longitude: 121.5167,
      },
      {
        id: "tolitoli",
        name: "Kab. Toli-Toli",
        latitude: 1.05,
        longitude: 120.8167,
      },
    ],
  },
  {
    id: "sulsel",
    name: "Sulawesi Selatan",
    cities: [
      {
        id: "makassar",
        name: "Kota Makassar",
        latitude: -5.1477,
        longitude: 119.4327,
      },
      {
        id: "palopo",
        name: "Kota Palopo",
        latitude: -2.9833,
        longitude: 120.2,
      },
      {
        id: "parepare",
        name: "Kota Parepare",
        latitude: -4.0167,
        longitude: 119.6333,
      },
      {
        id: "bantaeng",
        name: "Kab. Bantaeng",
        latitude: -5.5333,
        longitude: 119.95,
      },
      {
        id: "barru",
        name: "Kab. Barru",
        latitude: -4.4167,
        longitude: 119.6333,
      },
      { id: "bone", name: "Kab. Bone", latitude: -4.45, longitude: 120.3167 },
      {
        id: "bulukumba",
        name: "Kab. Bulukumba",
        latitude: -5.55,
        longitude: 120.2,
      },
      {
        id: "enrekang",
        name: "Kab. Enrekang",
        latitude: -3.5667,
        longitude: 119.8,
      },
      { id: "gowa", name: "Kab. Gowa", latitude: -5.2, longitude: 119.45 },
      {
        id: "jeneponto",
        name: "Kab. Jeneponto",
        latitude: -5.65,
        longitude: 119.6833,
      },
      {
        id: "kepulauan-selayar",
        name: "Kab. Kepulauan Selayar",
        latitude: -6.1667,
        longitude: 120.5167,
      },
      { id: "luwu", name: "Kab. Luwu", latitude: -3.2167, longitude: 120.35 },
      {
        id: "luwu-timur",
        name: "Kab. Luwu Timur",
        latitude: -2.5167,
        longitude: 121.15,
      },
      {
        id: "luwu-utara",
        name: "Kab. Luwu Utara",
        latitude: -2.5333,
        longitude: 120.3333,
      },
      { id: "maros", name: "Kab. Maros", latitude: -5.0, longitude: 119.6 },
      {
        id: "pangkajene",
        name: "Kab. Pangkajene dan Kepulauan",
        latitude: -4.8333,
        longitude: 119.5333,
      },
      {
        id: "pinrang",
        name: "Kab. Pinrang",
        latitude: -3.8,
        longitude: 119.65,
      },
      {
        id: "sidenreng-rappang",
        name: "Kab. Sidenreng Rappang",
        latitude: -3.9667,
        longitude: 119.8833,
      },
      {
        id: "sinjai",
        name: "Kab. Sinjai",
        latitude: -5.1333,
        longitude: 120.25,
      },
      {
        id: "soppeng",
        name: "Kab. Soppeng",
        latitude: -4.35,
        longitude: 119.8667,
      },
      {
        id: "takalar",
        name: "Kab. Takalar",
        latitude: -5.4167,
        longitude: 119.4667,
      },
      {
        id: "tanatoraja",
        name: "Kab. Tana Toraja",
        latitude: -3.05,
        longitude: 119.85,
      },
      {
        id: "toraja-utara",
        name: "Kab. Toraja Utara",
        latitude: -2.9167,
        longitude: 119.9,
      },
      { id: "wajo", name: "Kab. Wajo", latitude: -4.0667, longitude: 120.1333 },
    ],
  },
  {
    id: "sultra",
    name: "Sulawesi Tenggara",
    cities: [
      {
        id: "kendari",
        name: "Kota Kendari",
        latitude: -3.9985,
        longitude: 122.5129,
      },
      {
        id: "baubau",
        name: "Kota Baubau",
        latitude: -5.4667,
        longitude: 122.6167,
      },
      {
        id: "bombana",
        name: "Kab. Bombana",
        latitude: -4.6333,
        longitude: 121.6667,
      },
      { id: "buton", name: "Kab. Buton", latitude: -5.45, longitude: 122.7167 },
      {
        id: "buton-selatan",
        name: "Kab. Buton Selatan",
        latitude: -5.6167,
        longitude: 122.8833,
      },
      {
        id: "buton-tengah",
        name: "Kab. Buton Tengah",
        latitude: -5.2833,
        longitude: 122.5667,
      },
      {
        id: "buton-utara",
        name: "Kab. Buton Utara",
        latitude: -4.9833,
        longitude: 123.0833,
      },
      { id: "kolaka", name: "Kab. Kolaka", latitude: -4.05, longitude: 121.6 },
      {
        id: "kolaka-timur",
        name: "Kab. Kolaka Timur",
        latitude: -3.9667,
        longitude: 121.95,
      },
      {
        id: "kolaka-utara",
        name: "Kab. Kolaka Utara",
        latitude: -3.45,
        longitude: 121.2667,
      },
      { id: "konawe", name: "Kab. Konawe", latitude: -3.95, longitude: 122.2 },
      {
        id: "konawe-kepulauan",
        name: "Kab. Konawe Kepulauan",
        latitude: -4.15,
        longitude: 123.4167,
      },
      {
        id: "konawe-selatan",
        name: "Kab. Konawe Selatan",
        latitude: -4.2833,
        longitude: 122.4333,
      },
      {
        id: "konawe-utara",
        name: "Kab. Konawe Utara",
        latitude: -3.3333,
        longitude: 122.0833,
      },
      { id: "muna", name: "Kab. Muna", latitude: -4.85, longitude: 122.6833 },
      {
        id: "muna-barat",
        name: "Kab. Muna Barat",
        latitude: -4.9333,
        longitude: 122.4333,
      },
      {
        id: "wakatobi",
        name: "Kab. Wakatobi",
        latitude: -5.5,
        longitude: 123.5667,
      },
    ],
  },
  {
    id: "sulbar",
    name: "Sulawesi Barat",
    cities: [
      {
        id: "majene",
        name: "Kab. Majene",
        latitude: -3.5333,
        longitude: 118.9667,
      },
      {
        id: "mamasa",
        name: "Kab. Mamasa",
        latitude: -3.1333,
        longitude: 119.3667,
      },
      {
        id: "mamuju",
        name: "Kab. Mamuju",
        latitude: -2.6833,
        longitude: 118.8833,
      },
      {
        id: "mamuju-tengah",
        name: "Kab. Mamuju Tengah",
        latitude: -2.35,
        longitude: 119.3333,
      },
      {
        id: "pasangkayu",
        name: "Kab. Pasangkayu",
        latitude: -1.4,
        longitude: 119.4167,
      },
      {
        id: "polewali-mandar",
        name: "Kab. Polewali Mandar",
        latitude: -3.4167,
        longitude: 119.3333,
      },
    ],
  },
  {
    id: "maluku",
    name: "Maluku",
    cities: [
      {
        id: "ambon",
        name: "Kota Ambon",
        latitude: -3.6954,
        longitude: 128.1814,
      },
      { id: "tual", name: "Kota Tual", latitude: -5.6333, longitude: 132.75 },
      { id: "buru", name: "Kab. Buru", latitude: -3.4, longitude: 126.65 },
      {
        id: "buru-selatan",
        name: "Kab. Buru Selatan",
        latitude: -3.65,
        longitude: 126.6333,
      },
      {
        id: "kepulauan-aru",
        name: "Kab. Kepulauan Aru",
        latitude: -6.1333,
        longitude: 134.75,
      },
      {
        id: "maluku-barat-daya",
        name: "Kab. Maluku Barat Daya",
        latitude: -7.95,
        longitude: 128.55,
      },
      {
        id: "maluku-tengah",
        name: "Kab. Maluku Tengah",
        latitude: -3.35,
        longitude: 128.8833,
      },
      {
        id: "maluku-tenggara",
        name: "Kab. Maluku Tenggara",
        latitude: -5.85,
        longitude: 132.5833,
      },
      {
        id: "maluku-tenggara-barat",
        name: "Kab. Maluku Tenggara Barat",
        latitude: -7.6,
        longitude: 131.05,
      },
      {
        id: "seram-bagian-barat",
        name: "Kab. Seram Bagian Barat",
        latitude: -3.0833,
        longitude: 128.1167,
      },
      {
        id: "seram-bagian-timur",
        name: "Kab. Seram Bagian Timur",
        latitude: -3.1167,
        longitude: 130.75,
      },
    ],
  },
  {
    id: "malut",
    name: "Maluku Utara",
    cities: [
      {
        id: "ternate",
        name: "Kota Ternate",
        latitude: 0.7833,
        longitude: 127.3833,
      },
      {
        id: "tidore",
        name: "Kota Tidore Kepulauan",
        latitude: 0.6833,
        longitude: 127.4333,
      },
      {
        id: "halmahera-barat",
        name: "Kab. Halmahera Barat",
        latitude: 1.0833,
        longitude: 127.45,
      },
      {
        id: "halmahera-selatan",
        name: "Kab. Halmahera Selatan",
        latitude: -0.5833,
        longitude: 127.9,
      },
      {
        id: "halmahera-tengah",
        name: "Kab. Halmahera Tengah",
        latitude: 0.5333,
        longitude: 128.2667,
      },
      {
        id: "halmahera-timur",
        name: "Kab. Halmahera Timur",
        latitude: 1.0333,
        longitude: 128.4167,
      },
      {
        id: "halmahera-utara",
        name: "Kab. Halmahera Utara",
        latitude: 1.7,
        longitude: 128.0167,
      },
      {
        id: "kepulauan-sula",
        name: "Kab. Kepulauan Sula",
        latitude: -1.8833,
        longitude: 125.95,
      },
      {
        id: "pulau-morotai",
        name: "Kab. Pulau Morotai",
        latitude: 2.3167,
        longitude: 128.4333,
      },
      {
        id: "pulau-taliabu",
        name: "Kab. Pulau Taliabu",
        latitude: -1.85,
        longitude: 124.7833,
      },
    ],
  },
  {
    id: "papua",
    name: "Papua",
    cities: [
      {
        id: "jayapura",
        name: "Kota Jayapura",
        latitude: -2.5916,
        longitude: 140.669,
      },
      {
        id: "biak-numfor",
        name: "Kab. Biak Numfor",
        latitude: -1.1667,
        longitude: 136.0833,
      },
      {
        id: "jayapura-kab",
        name: "Kab. Jayapura",
        latitude: -2.9,
        longitude: 140.7,
      },
      {
        id: "keerom",
        name: "Kab. Keerom",
        latitude: -3.25,
        longitude: 140.8167,
      },
      {
        id: "kepulauan-yapen",
        name: "Kab. Kepulauan Yapen",
        latitude: -1.7833,
        longitude: 136.2167,
      },
      {
        id: "mamberamo-raya",
        name: "Kab. Mamberamo Raya",
        latitude: -2.5833,
        longitude: 138.4167,
      },
      {
        id: "mamberamo-tengah",
        name: "Kab. Mamberamo Tengah",
        latitude: -3.6,
        longitude: 138.9667,
      },
      { id: "sarmi", name: "Kab. Sarmi", latitude: -1.8667, longitude: 138.75 },
      {
        id: "supiori",
        name: "Kab. Supiori",
        latitude: -0.7333,
        longitude: 135.6,
      },
      {
        id: "waropen",
        name: "Kab. Waropen",
        latitude: -2.45,
        longitude: 136.8833,
      },
    ],
  },
  {
    id: "papua-barat",
    name: "Papua Barat",
    cities: [
      {
        id: "manokwari",
        name: "Kab. Manokwari",
        latitude: -0.8667,
        longitude: 134.0833,
      },
      {
        id: "fakfak",
        name: "Kab. Fakfak",
        latitude: -2.9333,
        longitude: 132.3,
      },
      {
        id: "kaimana",
        name: "Kab. Kaimana",
        latitude: -3.65,
        longitude: 133.75,
      },
      {
        id: "manokwari-selatan",
        name: "Kab. Manokwari Selatan",
        latitude: -1.5,
        longitude: 134.1333,
      },
      {
        id: "pegunungan-arfak",
        name: "Kab. Pegunungan Arfak",
        latitude: -1.3833,
        longitude: 133.8833,
      },
      {
        id: "teluk-bintuni",
        name: "Kab. Teluk Bintuni",
        latitude: -2.1333,
        longitude: 133.5333,
      },
      {
        id: "teluk-wondama",
        name: "Kab. Teluk Wondama",
        latitude: -2.6833,
        longitude: 134.5167,
      },
    ],
  },
  {
    id: "papua-barat-daya",
    name: "Papua Barat Daya",
    cities: [
      {
        id: "sorong",
        name: "Kota Sorong",
        latitude: -0.8833,
        longitude: 131.25,
      },
      {
        id: "maybrat",
        name: "Kab. Maybrat",
        latitude: -1.2333,
        longitude: 132.3333,
      },
      {
        id: "raja-ampat",
        name: "Kab. Raja Ampat",
        latitude: -0.5,
        longitude: 130.5167,
      },
      {
        id: "kab-sorong",
        name: "Kab. Sorong",
        latitude: -1.0333,
        longitude: 131.2833,
      },
      {
        id: "sorong-selatan",
        name: "Kab. Sorong Selatan",
        latitude: -1.7667,
        longitude: 132.15,
      },
      {
        id: "tambrauw",
        name: "Kab. Tambrauw",
        latitude: -0.6833,
        longitude: 132.6,
      },
    ],
  },
  {
    id: "papua-tengah",
    name: "Papua Tengah",
    cities: [
      {
        id: "deiyai",
        name: "Kab. Deiyai",
        latitude: -3.8667,
        longitude: 136.1,
      },
      {
        id: "dogiyai",
        name: "Kab. Dogiyai",
        latitude: -4.0333,
        longitude: 135.5,
      },
      {
        id: "intan-jaya",
        name: "Kab. Intan Jaya",
        latitude: -3.6167,
        longitude: 137.25,
      },
      { id: "mimika", name: "Kab. Mimika", latitude: -4.55, longitude: 136.9 },
      {
        id: "nabire",
        name: "Kab. Nabire",
        latitude: -3.3667,
        longitude: 135.4833,
      },
      {
        id: "paniai",
        name: "Kab. Paniai",
        latitude: -3.9167,
        longitude: 136.3333,
      },
      {
        id: "puncak",
        name: "Kab. Puncak",
        latitude: -3.9167,
        longitude: 137.15,
      },
      {
        id: "puncak-jaya",
        name: "Kab. Puncak Jaya",
        latitude: -4.0167,
        longitude: 137.0167,
      },
    ],
  },
  {
    id: "papua-pegunungan",
    name: "Papua Pegunungan",
    cities: [
      {
        id: "jayawijaya",
        name: "Kab. Jayawijaya",
        latitude: -4.1,
        longitude: 138.95,
      },
      {
        id: "lanny-jaya",
        name: "Kab. Lanny Jaya",
        latitude: -3.9333,
        longitude: 138.35,
      },
      {
        id: "nduga",
        name: "Kab. Nduga",
        latitude: -4.5333,
        longitude: 138.1833,
      },
      {
        id: "pegunungan-bintang",
        name: "Kab. Pegunungan Bintang",
        latitude: -4.4333,
        longitude: 140.4167,
      },
      {
        id: "tolikara",
        name: "Kab. Tolikara",
        latitude: -3.7667,
        longitude: 138.55,
      },
      {
        id: "yalimo",
        name: "Kab. Yalimo",
        latitude: -3.8333,
        longitude: 138.15,
      },
      {
        id: "yahukimo",
        name: "Kab. Yahukimo",
        latitude: -4.55,
        longitude: 139.0833,
      },
    ],
  },
  {
    id: "papua-selatan",
    name: "Papua Selatan",
    cities: [
      { id: "merauke", name: "Kab. Merauke", latitude: -8.5, longitude: 140.4 },
      {
        id: "asmat",
        name: "Kab. Asmat",
        latitude: -5.5667,
        longitude: 138.8833,
      },
      {
        id: "boven-digoel",
        name: "Kab. Boven Digoel",
        latitude: -5.6167,
        longitude: 140.3,
      },
      { id: "mappi", name: "Kab. Mappi", latitude: -6.0, longitude: 139.3 },
    ],
  },
];

// Flatten all cities with province info for search
export interface CityWithProvince extends City {
  provinceName: string;
  provinceId: string;
}

export const allCities: CityWithProvince[] = provinces.flatMap((province) =>
  province.cities.map((city) => ({
    ...city,
    provinceName: province.name,
    provinceId: province.id,
  })),
);

// Popular cities for quick selection (major cities)
export const popularCities: CityWithProvince[] = [
  allCities.find((c) => c.id === "jakarta-pusat")!,
  allCities.find((c) => c.id === "surabaya")!,
  allCities.find((c) => c.id === "bandung")!,
  allCities.find((c) => c.id === "medan")!,
  allCities.find((c) => c.id === "semarang")!,
  allCities.find((c) => c.id === "makassar")!,
  allCities.find((c) => c.id === "palembang")!,
  allCities.find((c) => c.id === "tangerang")!,
  allCities.find((c) => c.id === "depok")!,
  allCities.find((c) => c.id === "bekasi")!,
  allCities.find((c) => c.id === "yogyakarta")!,
  allCities.find((c) => c.id === "denpasar")!,
].filter(Boolean);

/**
 * Search cities by name
 * @param query - Search query
 * @param limit - Maximum results (default: 10)
 * @returns Matching cities
 */
export function searchCities(query: string, limit = 10): CityWithProvince[] {
  const normalizedQuery = query.toLowerCase().trim();

  if (!normalizedQuery) return popularCities.slice(0, limit);

  return allCities
    .filter(
      (city) =>
        city.name.toLowerCase().includes(normalizedQuery) ||
        city.provinceName.toLowerCase().includes(normalizedQuery),
    )
    .slice(0, limit);
}

/**
 * Get city by ID
 * @param id - City ID
 * @returns City or undefined
 */
export function getCityById(id: string): CityWithProvince | undefined {
  return allCities.find((city) => city.id === id);
}

/**
 * Get cities by province ID
 * @param provinceId - Province ID
 * @returns Cities in the province
 */
export function getCitiesByProvince(provinceId: string): City[] {
  const province = provinces.find((p) => p.id === provinceId);
  return province?.cities ?? [];
}

export default {
  provinces,
  allCities,
  popularCities,
  searchCities,
  getCityById,
  getCitiesByProvince,
};
